name: bcamp_data_platform_gcp
runtime:
  name: python
  options:
    virtualenv: venv
description: A minimal Google Cloud Python Pulumi program
config:
  pulumi:tags:
    value:
      pulumi:template: ""
